### ISSUE TITLE
How is the tenant id claims configured on the AD B2C

### ISSUE THREAD

**Issue by Gimly** [mrochon/b2cmultitenantapp#1]
Hi,

Thanks for that nice example! I'm trying to follow your code, but I'm lost at something. How is the TenantId part of the claims?

I've tried creating a new user in AD B2C and it doesn't have a TenantId claims, and I can't see where you could add this.

Thanks a lot for your help.

**Comment by mrochon** [comment]
B2C does not have the concept of multi-tenancy therefore in this sample user choice/assignment to application tenants (clinic 1, clinic 2, etc.) is kept in an SQL database. For example, when a user who has already been assigned to a tenant through either the 'create a new tenant' or 'join an existing tenant' functionality is signing in, Startup.Auth.cs determines the tenant id by looking in the database: https://github.com/mrochon/b2cmultitenantapp/blob/5b3605c5934482b0cfd7ae72997cf98199a94790/B2CMultiTenant/App_Start/Startup.Auth.cs#L94
Hope that helps.

**Comment by Gimly** [comment]
Yes, definitely helps, thanks. I was confused and thought that B2C had the concept of tenant built in.
